---
title: "DockerAssignment"
output: html_notebook
---


## Tasks:

### 1. Dreate a 5 by 10 matrix of random integers
```{r}
set.seed(10086)
randMatrix <- sample(1:100, 50, replace = TRUE)
(randMatrix <- matrix(randMatrix, nrow = 5, ncol = 10))
```
### 2. Define column names as cond1, cond2, cond3, cond4, cond5, ctrl1, ctrl2, ctrl3, ctrl4, ctrl5
```{r}
colnames(randMatrix) <- c("cond1", "cond2", "cond3", "cond4", "cond5", "ctrl1", "ctrl2", "ctrl3", "ctrl4", "ctrl5")
randMatrix
```
### 3. Define row names as gene1, gene2, gene3 ...
```{r}
row.names(randMatrix)<- c("gene1", "gene2", "gene3", "gene4", "gene5")
randMatrix
```
### 4. Compute the fold change for each gene.
```{r}
# Initiate a new column
logFoldChange <- c()

# Calculate the average log fold change for each gene
for (i in seq(nrow(randMatrix))){
    logFoldChange[i] <- log2(mean(randMatrix[i,1:5])/
                                 mean(randMatrix[i,6:10]))
}

# Add the column to matrix with name
cbind(randMatrix, logFoldChange = logFoldChange)
```

